import { render } from "@testing-library/react";
import type { ReactNode } from "react";
import { vi } from "vitest";
import {
	type ActionSequenceContextType,
	ActionSequenceCtx,
} from "../../src/contexts/ActionSequenceContext";
import { defaultCharacters } from "../../src/utils/actionSequence";

export function createMockContext(
	overrides: Partial<ActionSequenceContextType> = {},
): ActionSequenceContextType {
	const characters = defaultCharacters.map((c, i) => ({
		...c,
		id: `c${i + 1}`,
		name: `角色 ${i + 1}`,
		speed: "100",
		baseSpeed: "100",
	}));

	return {
		characters,
		setCharacters: vi.fn(),
		limitPreset: "150",
		setLimitPreset: vi.fn(),
		customLimit: "",
		setCustomLimit: vi.fn(),
		displayedLimit: "250",
		setDisplayedLimit: vi.fn(),
		resources: ["战技点"],
		setResources: vi.fn(),
		overrides: {},
		setOverrides: vi.fn(),
		ultOverrides: {},
		setUltOverrides: vi.fn(),
		skillOverrides: {},
		setSkillOverrides: vi.fn(),
		domainEndOverrides: {},
		setDomainEndOverrides: vi.fn(),
		speedAdjustments: {},
		setSpeedAdjustments: vi.fn(),
		skillTargets: {},
		setSkillTargets: vi.fn(),
		defaultSkillTargets: {},
		setDefaultSkillTargets: vi.fn(),
		odeSelections: {},
		setOdeSelections: vi.fn(),
		memeSelections: {},
		setMemeSelections: vi.fn(),
		lastMemeTarget: "",
		setLastMemeTarget: vi.fn(),
		ultInterrupts: {},
		setUltInterrupts: vi.fn(),
		fireflyBreakCounters: {},
		setFireflyBreakCounters: vi.fn(),
		godmodeExtraActions: {},
		setGodmodeExtraActions: vi.fn(),
		castoriceKillToggles: {},
		setCastoriceKillToggles: vi.fn(),
		icaKillToggles: {},
		setIcaKillToggles: vi.fn(),
		memeKillToggles: {},
		setMemeKillToggles: vi.fn(),
		evernightSelfDestructToggles: {},
		setEvernightSelfDestructToggles: vi.fn(),
		evernightThresholdBurstToggles: {},
		setEvernightThresholdBurstToggles: vi.fn(),
		fuaToggles: {},
		setFuaToggles: vi.fn(),
		hyacineE2Active: true,
		setHyacineE2Active: vi.fn(),
		meritTarget: undefined,
		setMeritTarget: vi.fn(),
		dancePartner: undefined,
		setDancePartner: vi.fn(),
		bondmateTarget: undefined,
		setBondmateTarget: vi.fn(),
		attackDisabled: {},
		setAttackDisabled: vi.fn(),
		saberAdvanceToggles: {},
		setSaberAdvanceToggles: vi.fn(),
		resourceValues: {},
		setResourceValues: vi.fn(),
		actions: [],
		importText: "",
		message: "",
		setMessage: vi.fn(),
		isExportingImage: false,
		setIsExportingImage: vi.fn(),
		selectedActionKeys: new Set(),
		setSelectedActionKeys: vi.fn(),
		actionMenuOpen: false,
		setActionMenuOpen: vi.fn(),
		actionMenuKey: null,
		setActionMenuKey: vi.fn(),
		actionMenuPos: 0,
		setActionMenuPos: vi.fn(),
		actionOperation: "advance",
		setActionOperation: vi.fn(),
		operationValue: "",
		setOperationValue: vi.fn(),
		operationSpeedMode: "absolute",
		setOperationSpeedMode: vi.fn(),
		advanceCeiling: "",
		setAdvanceCeiling: vi.fn(),
		draftInterruptCaster: "",
		setDraftInterruptCaster: vi.fn(),
		draftInterruptTiming: "before",
		setDraftInterruptTiming: vi.fn(),
		actionLimit: 150,
		displayedActionLimit: 250,
		characterNames: Object.fromEntries(characters.map((c) => [c.id, c.name])),
		characterKinds: Object.fromEntries(characters.map((c) => [c.id, c.kind])),
		charactersById: Object.fromEntries(characters.map((c) => [c.id, c])),
		memospriteTargets: [],
		imageExportRef: { current: null },
		addTarget: vi.fn(),
		removeTarget: vi.fn(),
		updateCharacter: vi.fn(),
		updateResourceValue: vi.fn(),
		resetSavedData: vi.fn(),
		clearAutosaveFile: vi.fn(),
		cancelHimekoNovaAssist: vi.fn(),
		updateSkillTarget: vi.fn(),
		updateActionSkill: vi.fn(),
		selectAction: vi.fn(),
		openActionMenu: vi.fn(),
		closeActionMenu: vi.fn(),
		applyActionOperation: vi.fn(),
		addResource: vi.fn(),
		updateResource: vi.fn(),
		removeResource: vi.fn(),
		buildExportData: vi.fn(),
		exportJson: vi.fn(),
		exportImage: vi.fn(),
		importJson: vi.fn(),
		importFromFile: vi.fn(),
		setImportText: vi.fn(),
		...overrides,
	};
}

export function renderWithContext(
	ui: ReactNode,
	ctxOverrides: Partial<ActionSequenceContextType> = {},
) {
	const ctx = createMockContext(ctxOverrides);
	return render(
		<ActionSequenceCtx.Provider value={ctx}>{ui}</ActionSequenceCtx.Provider>,
	);
}
