// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutosavePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function WriteBase64File(arg1:string,arg2:string):Promise<void>;

export function WritePngFile(arg1:string,arg2:string):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
